apiVersion: v1
kind: Service
metadata:
    name: web-service
spec:
    type: NodePort
    selector:
        component: web
    ports:
        - port: 80 #port to receive traffic on
          targetPort: 3000 #port that container is listening on
          nodePort: 30000 #exposes this via localhost port 30000 (DO NOT USE IN PRODUCTION)
